export const packageJson = {
  name: 'agora-app-builder',
  version: '1.0.0',
  scripts: {
    start: 'app-builder-init',
    'start:info': 'app-builder-init --info',
  },
  keywords: [],
  license: 'MIT',
  dependencies: {
    'agora-app-builder-cli': '0.0.10',
  },
};

export const region = [
  'US_EAST_1',
  'US_EAST_2',
  'US_WEST_1',
  'US_WEST_2',
  'EU_WEST_1',
  'EU_WEST_2',
  'EU_WEST_3',
  'EU_CENTRAL_1',
  'AP_SOUTHEAST_1',
  'AP_SOUTHEAST_2',
  'AP_NORTHEAST_1',
  'AP_NORTHEAST_2',
  'SA_EAST_1',
  'CA_CENTRAL_1',
  'AP_SOUTH_1',
  'CN_NORTH_1',
  'CN_NORTHWEST_1',
  'US_GOV_WEST_1',
];

export const extensions: string[] = [
  'jpeg',
  'jpg',
  'png',
  'webp',
  'tiff',
  'tif',
  'gif',
  'svg',
];

export const themeJson = {
  layoutProps: {topPinned: false},
  primaryButton: {
    width: '100%',
    backgroundColor: '#00AEFC',
    borderRadius: 100,
    maxWidth: 450,
    minWidth: 200,
    minHeight: 45,
  },
  primaryButtonText: {
    width: '100%',
    height: 45,
    lineHeight: 45,
    fontSize: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: '#fff',
  },
  secondaryBtn: {
    width: '100%',
    borderColor: '#00AEFC',
    borderWidth: 1,
    borderRadius: 100,
    maxWidth: 450,
    minWidth: 200,
    minHeight: 45,
  },
  secondaryButtonText: {
    width: '100%',
    height: 45,
    lineHeight: 45,
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '500',
    textAlignVertical: 'center',
    color: '#000',
  },
  textInput: {
    width: '100%',
    paddingLeft: 8,
    paddingRight: 8,
    borderColor: '#00AEFC',
    borderRadius: 100,
    borderWidth: 1,
    textAlign: 'center',
    color: '#333333',
    fontSize: 16,
    maxWidth: 450,
    minHeight: 45,
  },
  videoView: {
    flex: 12,
    backgroundColor: '#fff',
    flexDirection: 'row',
  },
  navHolder: {
    width: '100%',
    height: '6%',
    minHeight: 20,
    backgroundColor: '#f1f4f9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  controlsHolder: {
    minHeight: 50,
    maxHeight: '8%',
    backgroundColor: '#f1f4f9',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    position: 'relative',
    margin: 0,
    bottom: 0,
  },
  localButton: {
    backgroundColor: '#fff',
    borderRadius: 23,
    width: 46,
    height: 46,
    display: 'flex',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonIcon: {
    width: '70%',
    height: '70%',
    tintColor: '#00AEFC',
  },
};
